using System;
using System.Collections.Generic;
using System.Text;

namespace GNet.PInvoke
{
    public enum WinEvent : uint
    {
        EVENT_MIN = 0x0,
        EVENT_SYSTEM_SOUND = 0x1,
        EVENT_SYSTEM_ALERT = 0x2,
        EVENT_SYSTEM_FOREGROUND = 0x3,
        EVENT_SYSTEM_MENUSTART = 0x4,
        EVENT_SYSTEM_MENUEND = 0x5,
        EVENT_SYSTEM_MENUPOPUPSTART = 0x6,
        EVENT_SYSTEM_MENUPOPUPEND = 0x7,
        EVENT_SYSTEM_CAPTURESTART = 0x8,
        EVENT_SYSTEM_CAPTUREEND = 0x9,
        EVENT_SYSTEM_MOVESIZESTART = 0xa,
        EVENT_SYSTEM_MOVESIZEEND = 0xb,
        EVENT_SYSTEM_CONTEXTHELPSTART = 0xc,
        EVENT_SYSTEM_CONTEXTHELPEND = 0xd,
        EVENT_SYSTEM_DRAGDROPSTART = 0xe,
        EVENT_SYSTEM_DRAGDROPEND = 0xf,
        EVENT_SYSTEM_DIALOGSTART = 0x10,
        EVENT_SYSTEM_DIALOGEND = 0x11,
        EVENT_SYSTEM_SCROLLINGSTART = 0x12,
        EVENT_SYSTEM_SCROLLINGEND = 0x13,
        EVENT_SYSTEM_SWITCHSTART = 0x14,
        EVENT_SYSTEM_SWITCHEND = 0x15,
        EVENT_SYSTEM_MINIMIZESTART = 0x16,
        EVENT_SYSTEM_MINIMIZEEND = 0x17
    }
}
